---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: pi
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>6.7.0'
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: podinfo
  values:
    hpa:
      enabled: false
    replicaCount: 1
