apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize # https://github.com/stefanprodan/podinfo/tree/master/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
  patches:
    # Remove HPA
    - patch: |
        kind: HorizontalPodAutoscaler
        metadata:
          name: any
        $patch: delete
      target:
        kind: HorizontalPodAutoscaler
        name: podinfo
    # Scale to explicit number of replicas
    - patch: |
        - op: replaces
          path: /spec/replicas
          value: 1
      target:
        kind: Deployment
        name: podinfo
